# Generated by Django 4.2.3 on 2023-07-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facialRecognitionSite", "0002_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
